# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Portfolio
email: adrienne.mcd.21@gmail.com
description: A portfolio of web development projects
baseurl: "" # the base hostname & protocol for your site http://adriennemcd.com
twitter_username: adrienne_mcd
github_username:  adriennemcd

# Build settings
markdown: kramdown
permalink: /:title
excerpt_separator: <!--more-->
gems:
  - octopress-autoprefixer